### ISSUE TITLE
How to generate images ?

### ISSUE THREAD

**Issue by ok1cdj** [tvecera/m5kpz#1]
Hi, can you help me how to generate images ? Trying to add new sensor.

**Comment by tvecera** [comment]
I use the program LCD Image Converter ([https://lcd-image-converter.riuson.com/en/about/](https://lcd-image-converter.riuson.com/en/about/)), there are also online converters, however, this program has worked well for me. 

After opening the image, just click on Options / Conversion, then click on the Image tab set as shown below and click on the Show Preview button.

![Screenshot 2024-01-26 at 7 57 25](https://github.com/tvecera/m5kpz/assets/7688783/bc0e8863-2d3b-4485-8a03-78cb23c72959)

**Comment by ok1cdj** [comment]
Thanks will try it during weekend.

**Comment by ok1cdj** [comment]
Thanks, working for me....
